##Data Loading , Storage and File Formats
#DataFrame

In [ ]:
import pandas as pd

In [ ]:
data={
    "Name":["Amit","Riya","Rahul","Priya","Karan"],
    "Age":[20,21,20,22,21],
    "Department":["CSE","IT","CSE","ECE","IT"],
    "Marks":[85,90,78,88,76]
}
df=pd.DataFrame(data)
df

    Name  Age Department  Marks
0   Amit   20        CSE     85
1   Riya   21         IT     90
2  Rahul   20        CSE     78
3  Priya   22        ECE     88
4  Karan   21         IT     76

#Include 5 more rows in the dataframe and convert to different file formats and compare the file size

In [ ]:
import pandas as pd

data = {
    "Name": ["Amit", "Riya", "Rahul", "Priya", "Karan",
             "Neha", "Arjun", "Sneha", "Vikram", "Anjali"],

    "Age": [20, 21, 20, 22, 21, 19, 22, 20, 21, 19],

    "Department": ["CSE", "IT", "CSE", "ECE", "IT",
                   "CSE", "ECE", "IT", "CSE", "ECE"],

    "Marks": [85, 90, 78, 88, 76, 92, 81, 87, 89, 95]
}

df = pd.DataFrame(data)
print(df)

     Name  Age Department  Marks
0    Amit   20        CSE     85
1    Riya   21         IT     90
2   Rahul   20        CSE     78
3   Priya   22        ECE     88
4   Karan   21         IT     76
5    Neha   19        CSE     92
6   Arjun   22        ECE     81
7   Sneha   20         IT     87
8  Vikram   21        CSE     89
9  Anjali   19        ECE     95

In [ ]:
df.to_csv("df_csvoutput.csv",index=False)
df_csv=pd.read_csv("/content/df_csvoutput.csv")
print(df_csv.head())

    Name  Age Department  Marks
0   Amit   20        CSE     85
1   Riya   21         IT     90
2  Rahul   20        CSE     78
3  Priya   22        ECE     88
4  Karan   21         IT     76

In [ ]:
df.to_excel("df_exceloutput.xlsx",index=False)
df_excel=pd.read_excel("/content/df_exceloutput.xlsx")
print(df_excel.tail())

     Name  Age Department  Marks
5    Neha   19        CSE     92
6   Arjun   22        ECE     81
7   Sneha   20         IT     87
8  Vikram   21        CSE     89
9  Anjali   19        ECE     95

In [ ]:
df.to_json("df_jsonoutput.json",orient="records",indent=4)
df_json=pd.read_json("/content/df_jsonoutput.json")
print(df_json.head())

    Name  Age Department  Marks
0   Amit   20        CSE     85
1   Riya   21         IT     90
2  Rahul   20        CSE     78
3  Priya   22        ECE     88
4  Karan   21         IT     76

In [ ]:
df.to_parquet("df_parquetoutput.parquet",index=False)

In [ ]:
#Insert the dataframe
print("Shape of the dataframe:",df.shape)
print("Print 3 rows:\n",df.head(3))
print("Last 2 rows:\n",df.tail(2))
print("columns:",df.columns.tolist)
print("Data types:\n",df.dtypes)
print("Information:\n",df.info())
print("Statistics of data frame:\n",df.describe())

Shape of the dataframe: (5, 4)
Print 3 rows:
     Name  Age Department  Marks
0   Amit   20        CSE     85
1   Riya   21         IT     90
2  Rahul   20        CSE     78
Last 2 rows:
     Name  Age Department  Marks
3  Priya   22        ECE     88
4  Karan   21         IT     76
columns: <bound method IndexOpsMixin.tolist of Index(['Name', 'Age', 'Department', 'Marks'], dtype='object')>
Data types:
 Name          object
Age            int64
Department    object
Marks          int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         5 non-null      int64
 2   Department  5 non-null      object
 3   Marks       5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes
Information:
 None
Statistics of data frame:
             Age     Marks
count   5.00000   5.00000
mean   20.80000  83.40000
std     0.83666   6.14817
min    20.00000  76.00000
25%    20.00000  78.00000
50%    21.00000  85.00000
75%    21.00000  88.00000
max    22.00000  90.00000

In [ ]:
Iris=pd.read_csv("/content/Iris.csv")
Iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
print(Iris.shape)
print(Iris.columns)
print(Iris.dtypes)

(150, 6)
Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')
Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

#File Formats
##1.csv
##2.excel
##3.json
##4.parquet

In [ ]:
#load the dataset in file format
Iris.to_csv("Iris_csvoutput.csv",index=False)
#Read the saved dataset
Iris_csv=pd.read_csv("/content/Iris_csvoutput.csv")
print(Iris_csv.head)

<bound method NDFrame.head of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]>

In [ ]:
Iris.to_excel("Iris_exceloutput.xlsx",index=False)
#load
Iris_excel=pd.read_excel("/content/Iris_exceloutput.xlsx")
print(Iris_excel.tail(10))

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
140  141            6.7           3.1            5.6           2.4
141  142            6.9           3.1            5.1           2.3
142  143            5.8           2.7            5.1           1.9
143  144            6.8           3.2            5.9           2.3
144  145            6.7           3.3            5.7           2.5
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
140  Iris-virginica
141  Iris-virginica
142  Iris-virginica
143  Iris-virginica
144  Iris-virginica
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

In [ ]:
#Json file format
Iris.to_json("Iris_jsonoutput.json",orient="records",indent=4)
Iris_json=pd.read_json("/content/Iris_jsonoutput.json")
Iris_json.head(5)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
#parquet file format
Iris.to_parquet("Iris_parquetoutput.parquet",index=False)
Iris_parquet=pd.read_parquet("/content/Iris_parquetoutput.parquet")
print(Iris_parquet.head(3))

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa

In [ ]:
#compare the size of file format
import os
files=[
    "Iris_csvoutput.csv",
    "Iris_exceloutput.xlsx",
    "Iris_jsonoutput.json",
    "Iris_parquetoutput.parquet"
]
for file in files:
  size=os.path.getsize(file)
  print(f"{file}:{size} bytes")

Iris_csvoutput.csv:5107 bytes
Iris_exceloutput.xlsx:9207 bytes
Iris_jsonoutput.json:26794 bytes
Iris_parquetoutput.parquet:5932 bytes

In [ ]:
#load the selected columns
Iris_small=pd.read_csv("/content/Iris.csv",usecols=["SepalLengthCm","SepalWidthCm","Species"])
print(Iris_small.head(3))

   SepalLengthCm  SepalWidthCm      Species
0            5.1           3.5  Iris-setosa
1            4.9           3.0  Iris-setosa
2            4.7           3.2  Iris-setosa

In [ ]:
#filter the data
result=Iris[Iris["SepalLengthCm"]>6]
result.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
50,51,7.0,3.2,4.7,1.4,Iris-versicolor
51,52,6.4,3.2,4.5,1.5,Iris-versicolor
52,53,6.9,3.1,4.9,1.5,Iris-versicolor
54,55,6.5,2.8,4.6,1.5,Iris-versicolor
56,57,6.3,3.3,4.7,1.6,Iris-versicolor